import assert from "node:assert/strict";
import { test } from "node:test";
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { chromium } from "playwright";
import { startManager } from "../src/server.ts";
import { mockProvider, temporaryAgent } from "./fixtures.ts";
import { getBuiltinModels } from "@earendil-works/pi-ai/providers/all";
import { LimitCatalog } from "../src/limits.ts";

test("browser workflow: connect, discover, configure, test and save a provider", async (t) => {
  const temp = await temporaryAgent(); t.after(temp.close);
  const upstream = await mockProvider(); t.after(upstream.close);
  const manager = await startManager(temp.dir); t.after(manager.close);
  // Use installed Edge on Windows; Playwright Chromium elsewhere.
  const browser = await chromium.launch({ ...(process.platform === "win32" ? { channel: "msedge" } : {}), headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1440, height: 1040 } });
  const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
  page.on("dialog", (dialog) => void dialog.accept());
  await page.goto(manager.url);
  await page.locator("#version").filter({ hasText: "0.85.1" }).waitFor();
  await page.locator("#provider-id").fill("my-gateway");
  await page.locator("#base-url").fill(`${upstream.base}/v1`);
  await page.locator("#api-key").fill("browser-test-secret");
  await page.locator("#test-connection").click();
  await page.locator("#diagnostics").filter({ hasText: "HTTP 200" }).waitFor();
  await page.locator("#fetch-models").click();
  await page.locator("#models-body tr").first().waitFor();
  assert.equal(await page.locator("#models-body tr").count(), 2);
  await page.locator("#select-all").check();
  await page.locator("#models-body tr").first().getByRole("button", { name: "Edit", exact: true }).click();
  await page.locator("#edit-context").fill("64000");
  await page.locator("#model-form button[type=submit]").click();
  const connectionDiagnostics = await page.locator("#diagnostics").textContent();
  const model = page.locator('.model-row[data-model-id="model-a"]');
  const results = page.locator('.model-results[data-result-model="model-a"]');
  await model.getByRole("button", { name: "Test chat", exact: true }).click();
  await results.locator('[data-capability="chat"][data-outcome="supported"]').waitFor();
  assert.equal(await page.locator("#diagnostics").textContent(), connectionDiagnostics);
  await model.getByRole("button", { name: "Check capabilities", exact: true }).click();
  await results.locator(".probe-progress").filter({ hasText: "Tests finished" }).waitFor();
  assert.equal(await results.locator('[data-outcome="supported"]').count(), 4);
  await results.getByRole("button", { name: "Apply verified capabilities" }).click();
  await page.locator("#save-provider").click();
  await page.locator("#notice").filter({ hasText: "Provider saved" }).waitFor();
  assert.equal(await page.locator("#api-key").inputValue(), "");
  assert.equal((await page.content()).includes("browser-test-secret"), false);
  await page.locator("#models-body tr").first().getByRole("button", { name: "Set default" }).click();
  await page.locator("#notice").filter({ hasText: "Default saved" }).waitFor();
  const saved = JSON.parse(await readFile(join(temp.dir, "models.json"), "utf8"));
  assert.equal(saved.providers["my-gateway"].models[0].contextWindow, 64000);
  assert.equal(saved.providers["my-gateway"].models.length, 2);
  assert.equal(saved.providers["my-gateway"].models[0].reasoning, true);
  assert.deepEqual(saved.providers["my-gateway"].models[0].input, ["text", "image"]);
  assert.equal(saved.providers["my-gateway"].models[0].checks, undefined);
  assert.equal(await results.locator('[data-outcome="supported"]').count(), 4);
  await page.locator("#language").selectOption("id");
  assert.equal(await page.locator("#save-provider").textContent(), "Simpan provider");
  assert.match(await results.textContent() || "", /Tool call valid/);
  const output = resolve("test-results"); await mkdir(output, { recursive: true });
  await page.screenshot({ path: join(output, "provider-manager-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: join(output, "provider-manager-mobile.png"), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  assert.ok(await results.evaluate((el) => el.getBoundingClientRect().right <= window.innerWidth));
  assert.ok(await results.evaluate((el) => [...el.querySelectorAll("*")].every((node) => parseFloat(getComputedStyle(node).fontSize) >= 16)));
  await model.getByRole("button", { name: "Tutup hasil" }).click();
  assert.equal(await results.count(), 0);
  await model.getByRole("button", { name: "Lihat hasil" }).click();
  await results.waitFor();
  await page.locator("#base-url").fill(`${upstream.base}/changed`);
  assert.equal(await results.count(), 0);
  assert.deepEqual(errors, []);
});

test("default provider status explains deletion and moving the default enables removal", async (t) => {
  const temp = await temporaryAgent(); t.after(temp.close);
  await writeFile(join(temp.dir, "models.json"), JSON.stringify({ providers: {
    alpha: { api: "openai-completions", baseUrl: "https://alpha.example/v1", models: [{ id: "alpha-model-ux" }] },
    beta: { api: "openai-completions", baseUrl: "https://beta.example/v1", models: [{ id: "beta-model-ux" }] },
  } }));
  await writeFile(join(temp.dir, "settings.json"), JSON.stringify({ defaultProvider: "alpha", defaultModel: "alpha-model-ux" }));
  const manager = await startManager(temp.dir); t.after(manager.close);
  const browser = await chromium.launch({ ...(process.platform === "win32" ? { channel: "msedge" } : {}), headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  page.on("dialog", (dialog) => void dialog.accept());
  await page.goto(manager.url);
  await page.locator("#provider-id").waitFor();
  assert.match(await page.locator("#version").textContent() || "", /Manager 0\.1\.2/);

  const alpha = page.locator("#provider-list button", { hasText: "alpha" });
  const beta = page.locator("#provider-list button", { hasText: "beta" });
  assert.match(await alpha.textContent() || "", /Pi default/);
  await page.locator("#default-provider-note").filter({ hasText: "cannot be deleted" }).waitFor();
  assert.match(await page.locator('[data-i18n="defaultActionHelp"]').textContent() || "", /Set default/);

  await page.locator("#delete-provider").click();
  await page.locator("#notice.warning").filter({ hasText: "Set default" }).waitFor();
  assert.ok(JSON.parse(await readFile(join(temp.dir, "models.json"), "utf8")).providers.alpha);

  await beta.click();
  await page.locator('.model-row[data-model-id="beta-model-ux"]').getByRole("button", { name: "Set default", exact: true }).click();
  await page.locator("#notice").filter({ hasText: "Default saved" }).waitFor();
  assert.match(await beta.textContent() || "", /Pi default/);
  assert.doesNotMatch(await alpha.textContent() || "", /Pi default/);

  await alpha.click();
  assert.equal(await page.locator("#default-provider-note").isHidden(), true);
  await page.locator("#delete-provider").click();
  await page.locator("#provider-list button", { hasText: "alpha" }).waitFor({ state: "detached" });
  const saved = JSON.parse(await readFile(join(temp.dir, "models.json"), "utf8"));
  assert.equal(saved.providers.alpha, undefined);
  assert.ok(saved.providers.beta);
});

test("model results stay isolated, inconclusive checks stay explicit, and cancellation stops the queue", async (t) => {
  const temp = await temporaryAgent(); t.after(temp.close);
  const upstream = await mockProvider({ behavior: "ignored", delayMs: 200, rejectModel: "model-b" }); t.after(upstream.close);
  const manager = await startManager(temp.dir); t.after(manager.close);
  const browser = await chromium.launch({ ...(process.platform === "win32" ? { channel: "msedge" } : {}), headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  await page.goto(manager.url);
  await page.locator("#version").filter({ hasText: "0.85.1" }).waitFor();
  await page.locator("#provider-id").fill("gateway");
  await page.locator("#base-url").fill(`${upstream.base}/v1`);
  await page.locator("#api-key").fill("test-secret");
  await page.locator("#fetch-models").click();
  const first = page.locator('.model-row[data-model-id="model-a"]');
  const second = page.locator('.model-row[data-model-id="model-b"]');
  const firstResult = page.locator('.model-results[data-result-model="model-a"]');
  const secondResult = page.locator('.model-results[data-result-model="model-b"]');
  await first.getByRole("button", { name: "Check capabilities" }).click();
  await firstResult.locator(".probe-progress").filter({ hasText: "Tests finished" }).waitFor();
  assert.equal(await firstResult.locator('[data-outcome="inconclusive"]').count(), 3);
  assert.equal(await firstResult.getByRole("button", { name: "Apply verified capabilities" }).count(), 0);
  const priorResult = await firstResult.textContent();
  const beforeFailure = upstream.requests.length;
  await second.getByRole("button", { name: "Check capabilities" }).click();
  await secondResult.locator(".probe-progress").filter({ hasText: "Tests stopped" }).waitFor();
  await secondResult.locator('[data-capability="chat"][data-outcome="failed"]').waitFor();
  assert.match(await secondResult.textContent() || "", /HTTP 403/);
  assert.equal(upstream.requests.length, beforeFailure + 1);
  assert.equal(await firstResult.textContent(), priorResult);
  assert.equal((await page.content()).includes("PRIVATE ERROR"), false);
  const beforeCancel = upstream.requests.length;
  await first.getByRole("button", { name: "Check capabilities" }).click();
  await firstResult.getByRole("button", { name: "Stop tests" }).click();
  await firstResult.locator(".probe-progress").filter({ hasText: "Tests stopped" }).waitFor();
  assert.equal(await firstResult.locator('[data-outcome="queued"], [data-outcome="running"]').count(), 0);
  assert.ok(upstream.requests.length <= beforeCancel + 1);
  assert.equal(await first.getByRole("button", { name: "Test chat" }).isEnabled(), true);
});

test("gateway role rejection has an actionable inline fix that persists for Pi", async (t) => {
  const temp = await temporaryAgent(); t.after(temp.close);
  const upstream = await mockProvider({ rejectDeveloperRole: true }); t.after(upstream.close);
  const manager = await startManager(temp.dir); t.after(manager.close);
  const browser = await chromium.launch({ ...(process.platform === "win32" ? { channel: "msedge" } : {}), headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(manager.url);
  await page.locator("#version").filter({ hasText: "0.85.1" }).waitFor();
  await page.locator("#provider-id").fill("gateway");
  await page.locator("#base-url").fill(`${upstream.base}/v1`);
  await page.locator("#api-key").fill("test-secret");
  await page.locator("#fetch-models").click();
  await page.locator("#select-all").check();
  const model = page.locator('.model-row[data-model-id="model-a"]');
  const results = page.locator('.model-results[data-result-model="model-a"]');
  await model.getByRole("button", { name: "Edit", exact: true }).click();
  await page.locator("#edit-reasoning").selectOption("yes");
  await page.locator("#model-form button[type=submit]").click();
  const before = upstream.requests.length;
  await model.getByRole("button", { name: "Check capabilities" }).click();
  await results.locator(".probe-progress").filter({ hasText: "Tests stopped" }).waitFor();
  assert.equal(upstream.requests.length, before + 1);
  assert.match(await results.textContent() || "", /HTTP 422/);
  assert.match(await results.textContent() || "", /gateway rejects Pi's developer role/);
  assert.equal((await page.content()).includes("PRIVATE ERROR"), false);
  await results.getByRole("button", { name: "Edit system prompt role" }).click();
  await page.locator("#edit-system-role").selectOption("system");
  await page.locator("#model-form button[type=submit]").click();
  assert.equal(await results.count(), 0);
  await model.getByRole("button", { name: "Check capabilities" }).click();
  await results.locator(".probe-progress").filter({ hasText: "Tests finished" }).waitFor();
  assert.equal(await results.locator('[data-outcome="supported"]').count(), 4);
  await page.locator("#save-provider").click();
  await page.locator("#notice").filter({ hasText: "Provider saved" }).waitFor();
  const saved = JSON.parse(await readFile(join(temp.dir, "models.json"), "utf8"));
  assert.equal(saved.providers.gateway.models[0].compat.supportsDeveloperRole, false);
  assert.equal(saved.providers.gateway.models[0].reasoning, true);
  assert.equal(saved.providers.gateway.models[1].compat, undefined);
  await page.locator("#refresh-state").click();
  await page.locator("#notice").filter({ hasText: "Configuration reloaded" }).waitFor();
  await page.locator("#language").selectOption("id");
  await model.getByRole("button", { name: "Edit", exact: true }).click();
  assert.equal(await page.locator("#edit-system-role").inputValue(), "system");
  assert.equal(await page.locator('[data-i18n="systemRole"]').textContent(), "Role system prompt (OpenAI)");
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.locator("#model-dialog").evaluate((el) => el.scrollWidth <= el.clientWidth));
  assert.ok(await page.locator("#edit-system-role").evaluate((el) => parseFloat(getComputedStyle(el).fontSize) >= 16));
  assert.deepEqual(errors, []);
});

test("provider-wide system role covers new models and displays individual overrides", async (t) => {
  const temp = await temporaryAgent(); t.after(temp.close);
  const upstream = await mockProvider({ rejectDeveloperRole: true }); t.after(upstream.close);
  const manager = await startManager(temp.dir); t.after(manager.close);
  const browser = await chromium.launch({ ...(process.platform === "win32" ? { channel: "msedge" } : {}), headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  await page.goto(manager.url);
  await page.locator("#version").filter({ hasText: "0.85.1" }).waitFor();
  await page.locator("#provider-id").fill("gateway");
  await page.locator("#base-url").fill(`${upstream.base}/v1`);
  await page.locator("#api-key").fill("test-secret");
  await page.locator("#fetch-models").click();
  await page.locator("#select-all").check();
  for (const id of ["model-a", "model-b"]) {
    await page.locator(`.model-row[data-model-id="${id}"]`).getByRole("button", { name: "Edit", exact: true }).click();
    await page.locator("#edit-reasoning").selectOption("yes");
    if (id === "model-b") await page.locator("#edit-system-role").selectOption("developer");
    await page.locator("#model-form button[type=submit]").click();
  }
  const first = page.locator('.model-row[data-model-id="model-a"]');
  const second = page.locator('.model-row[data-model-id="model-b"]');
  const results = page.locator('.model-results[data-result-model="model-a"]');
  await first.getByRole("button", { name: "Test chat", exact: true }).click();
  await results.locator('[data-outcome="failed"]').waitFor();
  await page.locator("#provider-system-role").selectOption("system");
  assert.equal(await results.count(), 0);
  assert.match(await first.textContent() || "", /Provider default: system/);
  assert.match(await second.textContent() || "", /Model override: developer/);
  await first.getByRole("button", { name: "Test chat", exact: true }).click();
  await results.locator('[data-outcome="supported"]').waitFor();
  await page.locator("#add-model").click();
  await page.locator("#edit-model-id").fill("new-model");
  await page.locator("#edit-reasoning").selectOption("yes");
  await page.locator("#model-form button[type=submit]").click();
  const added = page.locator('.model-row[data-model-id="new-model"]');
  assert.match(await added.textContent() || "", /Provider default: system/);
  await added.getByRole("button", { name: "Test chat", exact: true }).click();
  await page.locator('.model-results[data-result-model="new-model"] [data-outcome="supported"]').waitFor();
  await page.locator("#save-provider").click();
  await page.locator("#notice").filter({ hasText: "Provider saved" }).waitFor();
  const saved = JSON.parse(await readFile(join(temp.dir, "models.json"), "utf8"));
  assert.equal(saved.providers.gateway.compat.supportsDeveloperRole, false);
  assert.equal(saved.providers.gateway.models[0].compat, undefined);
  assert.equal(saved.providers.gateway.models[1].compat.supportsDeveloperRole, true);
  assert.equal(saved.providers.gateway.models[2].compat, undefined);
  await page.reload();
  await page.locator("#auth-source").filter({ hasText: "auth.json" }).waitFor();
  assert.equal(await page.locator("#provider-system-role").inputValue(), "system");
  await page.locator("#language").selectOption("id");
  assert.match(await first.textContent() || "", /Default provider: system/);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  assert.ok(await page.locator("#provider-system-role").evaluate((el) => parseFloat(getComputedStyle(el).fontSize) >= 16));
});

test("model limits use endpoint defaults, keep manual edits, and fill existing catalog matches without silent saves", async (t) => {
  const temp = await temporaryAgent(); t.after(temp.close);
  const catalog = new LimitCatalog();
  const builtin = getBuiltinModels("openai").find((model) => catalog.lookup(model.id).contextWindow && catalog.lookup(model.id).maxTokens)!;
  assert.ok(builtin);
  const entries = [
    { id: builtin.id, context_length: 48000, max_output_tokens: 12000 },
    { id: "endpoint-model", context_length: 256000, max_output_tokens: 32000 },
    { id: "manual-model", context_length: 128000, max_output_tokens: 8192 },
    { id: "unknown-local-alias" },
  ];
  const upstream = await mockProvider({ modelList: entries }); t.after(upstream.close);
  const original = JSON.stringify({ providers: { gateway: { api: "openai-completions", baseUrl: `${upstream.base}/v1`,
    models: [{ id: builtin.id }, { id: "manual-model", contextWindow: 16000 }],
  } } });
  await writeFile(join(temp.dir, "models.json"), original);
  const manager = await startManager(temp.dir); t.after(manager.close);
  const browser = await chromium.launch({ ...(process.platform === "win32" ? { channel: "msedge" } : {}), headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
  page.on("dialog", (dialog) => void dialog.accept());
  await page.goto(manager.url);
  const known = page.locator(`.model-row[data-model-id="${builtin.id}"]`);
  const manual = page.locator('.model-row[data-model-id="manual-model"]');
  await known.locator('[data-limit="contextWindow"]').filter({ hasText: "Pi catalog reference" }).waitFor();
  assert.equal(await readFile(join(temp.dir, "models.json"), "utf8"), original);
  await page.locator("#api-key").fill("limit-test-secret");
  await page.locator("#fetch-models").click();
  await known.locator('[data-limit="contextWindow"]').filter({ hasText: "Endpoint metadata" }).waitFor();
  await known.getByRole("button", { name: "Edit", exact: true }).click();
  assert.equal(await page.locator("#edit-context").inputValue(), "48000");
  assert.equal(await page.locator("#edit-max").inputValue(), "12000");
  await page.locator("#close-dialog").click();
  await manual.getByRole("button", { name: "Edit", exact: true }).click();
  assert.equal(await page.locator("#edit-context").inputValue(), "16000");
  assert.equal(await page.locator("#edit-max").inputValue(), "8192");
  assert.match(await page.locator("#edit-context-source").textContent() || "", /Saved \/ custom value.*Detected value/);
  await page.locator("#edit-max").fill("");
  await page.locator("#model-form button[type=submit]").click();
  await page.locator("#fill-limits").click();
  await manual.getByRole("button", { name: "Edit", exact: true }).click();
  assert.equal(await page.locator("#edit-context").inputValue(), "16000");
  assert.equal(await page.locator("#edit-max").inputValue(), "8192");
  await page.locator("#close-dialog").click();
  const endpoint = page.locator('.model-row[data-model-id="endpoint-model"]');
  await endpoint.getByRole("button", { name: "Edit", exact: true }).click();
  assert.equal(await page.locator("#edit-context").inputValue(), "256000");
  await page.locator("#edit-context").fill("64000");
  await page.locator("#edit-max").fill("4096");
  await page.locator("#model-form button[type=submit]").click();
  entries[1].context_length = 512000; entries[1].max_output_tokens = 64000;
  const count = upstream.requests.length;
  await page.locator("#fetch-models").click();
  await page.waitForFunction(() => !document.getElementById("fetch-models")?.hasAttribute("disabled"));
  assert.equal(upstream.requests.length, count + 1);
  await endpoint.getByRole("button", { name: "Edit", exact: true }).click();
  assert.equal(await page.locator("#edit-context").inputValue(), "64000");
  assert.equal(await page.locator("#edit-max").inputValue(), "4096");
  await page.locator("#use-model-limits").click();
  assert.equal(await page.locator("#edit-context").inputValue(), "512000");
  assert.equal(await page.locator("#edit-max").inputValue(), "64000");
  await page.locator("#model-form button[type=submit]").click();
  await page.locator("#select-all").check();
  const saveResponse = page.waitForResponse((response) => response.url().endsWith("/api/save"));
  await page.locator("#save-provider").click();
  const response = await saveResponse;
  const result = await response.json();
  assert.equal(response.status(), 200, JSON.stringify(result));
  assert.equal(result.warning, undefined, JSON.stringify(result));
  await page.locator("#notice").filter({ hasText: "Provider saved" }).waitFor();
  const saved = JSON.parse(await readFile(join(temp.dir, "models.json"), "utf8"));
  assert.equal(saved.providers.gateway.models.find((m: any) => m.id === "endpoint-model").maxTokens, 64000);
  assert.equal(saved.providers.gateway.models.find((m: any) => m.id === "manual-model").contextWindow, 16000);
  assert.equal(saved.providers.gateway.models.find((m: any) => m.id === "unknown-local-alias").contextWindow, undefined);
  assert.equal(JSON.stringify(saved).includes("limitHints"), false);
  assert.equal(JSON.stringify(saved).includes("limitSources"), false);
  await page.locator("#base-url").fill(`${upstream.base}/changed`);
  await endpoint.getByRole("button", { name: "Edit", exact: true }).click();
  assert.equal(await page.locator("#edit-context").inputValue(), "512000"); // Saved values survive connection edits.
  await page.locator("#close-dialog").click();
  await page.locator("#language").selectOption("id");
  assert.match(await endpoint.locator('[data-limit="maxTokens"]').textContent() || "", /Maksimal token output/);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  assert.ok(await endpoint.locator(".model-limits").evaluate((el) => [...el.querySelectorAll("*")].every((node) => parseFloat(getComputedStyle(node).fontSize) >= 16)));
  assert.ok(upstream.requests.every((request) => request.path.endsWith("/models")));
  assert.deepEqual(errors, []);
});

test("manual model ID lookup fills catalog defaults without overwriting typing or applying stale responses", async (t) => {
  const temp = await temporaryAgent(); t.after(temp.close);
  const catalog = new LimitCatalog();
  const builtin = getBuiltinModels("openai").find((model) => catalog.lookup(model.id).contextWindow && catalog.lookup(model.id).maxTokens)!;
  const hints = catalog.lookup(builtin.id);
  const manager = await startManager(temp.dir); t.after(manager.close);
  const browser = await chromium.launch({ ...(process.platform === "win32" ? { channel: "msedge" } : {}), headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  await page.goto(manager.url);
  await page.locator("#version").filter({ hasText: "0.85.1" }).waitFor();
  await page.locator("#add-model").click();
  await page.locator("#edit-model-id").fill(builtin.id);
  await page.locator("#edit-context-source").filter({ hasText: "Pi catalog reference" }).waitFor();
  assert.equal(await page.locator("#edit-context").inputValue(), String(hints.contextWindow!.value));
  assert.equal(await page.locator("#edit-max").inputValue(), String(hints.maxTokens!.value));
  await page.locator("#edit-context").fill("64000");
  await page.locator("#edit-model-id").fill("unknown-local-alias");
  await page.locator("#limit-lookup-status").filter({ hasText: "Metadata reference" }).waitFor();
  assert.equal(await page.locator("#edit-context").inputValue(), "64000");
  assert.equal(await page.locator("#edit-max").inputValue(), "");
  await page.locator("#close-dialog").click();
  let release!: () => void;
  const paused = new Promise<void>((resolve) => { release = resolve; });
  let started!: () => void;
  const startedPromise = new Promise<void>((resolve) => { started = resolve; });
  await page.route("**/api/model-limits", async (route) => {
    if (route.request().postDataJSON().modelId === builtin.id) { started(); await paused; }
    await route.continue();
  });
  await page.locator("#add-model").click();
  await page.locator("#edit-model-id").fill(builtin.id);
  await startedPromise;
  await page.locator("#edit-model-id").fill("another-unknown-alias");
  release();
  await page.waitForResponse((response) => response.url().endsWith("/api/model-limits") && response.request().postDataJSON().modelId === "another-unknown-alias");
  assert.equal(await page.locator("#edit-context").inputValue(), "");
  assert.equal(await page.locator("#edit-max").inputValue(), "");
  await page.locator("#model-form button[type=submit]").click();
  await page.locator('.model-row[data-model-id="another-unknown-alias"]').waitFor();
  assert.equal(await page.locator(".model-row").count(), 1);
});
